apiVersion: batch/v1
kind: CronJob
metadata:
  name: project-wikipedia
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: wikipedia
            image: PROJECT/WIKIPEDIA
            env:
            - name: TODO_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: project-conf
                  key: TODO_BACKEND_URL
          restartPolicy: Never