apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./../../base

patches:
- path: app/deployment.yaml

namespace: project-staging
images:
- name: BACKUP
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/project-backup
  newTag: main-d472352a4e2f33bcd4144c89b95f8fe148ac2dc2
- name: TODO-APP
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/project-todo-app
  newTag: main-d472352a4e2f33bcd4144c89b95f8fe148ac2dc2
- name: TODO-BACKEND
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/project-todo-backend
  newTag: main-d472352a4e2f33bcd4144c89b95f8fe148ac2dc2
- name: TODO-BROADCASTER
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/project-todo-broadcaster
  newTag: main-d472352a4e2f33bcd4144c89b95f8fe148ac2dc2
- name: WIKIPEDIA
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/project-todo-wikipedia
  newTag: main-d472352a4e2f33bcd4144c89b95f8fe148ac2dc2
