apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./../../base
- backup/job.yaml

patches:
- path: broadcaster/deployment.yaml
namespace: project
images:
- name: BACKUP
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/project-backup
  newTag: main-35e6ecdd6e7f18e69f33407b43942c9124dab491
- name: TODO-APP
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/project-todo-app
  newTag: main-35e6ecdd6e7f18e69f33407b43942c9124dab491
- name: TODO-BACKEND
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/project-todo-backend
  newTag: main-35e6ecdd6e7f18e69f33407b43942c9124dab491
- name: TODO-BROADCASTER
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/project-todo-broadcaster
  newTag: main-35e6ecdd6e7f18e69f33407b43942c9124dab491
- name: WIKIPEDIA
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/project-todo-wikipedia
  newTag: main-35e6ecdd6e7f18e69f33407b43942c9124dab491
