apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-backup-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-backup
  template:
    metadata:
      labels:
        app: project-backup
    spec:   
      volumes:
        - name: service-account-key
          configMap:
            name: project-secret-conf
            items:
            - key: "key.json"
              path: "private-key.json"
      containers: 
      - name: backup
        image: mluukkai/project-backup:12
        env:
        - name: BUCKET_NAME
          value: mluukkai_project_backups
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: project-conf
              key: DB_URL
        volumeMounts:
          - name: service-account-key
            mountPath: "/myapp/config"
            readOnly: true
