name: Release application

on:
  push:

env:
  PROJECT_ID:   ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER:  dwk-cluster
  GKE_ZONE:     europe-north1-b
  REGISTRY:     europe-north1-docker.pkg.dev
  REPOSITORY:   my-repository
  APP:          project-todo-app
  BACKEND:      project-todo-backend
  WIKI:         project-todo-wikipedia
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: 'Set up Docker Buildx'
        run: gcloud auth configure-docker "$REGISTRY"
          
      - name : 'Build and push todo-app'
        run: echo "APP_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$APP:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name : 'Build and push todo-app'
        run: |
          docker build --tag "$APP_IMAGE_TAG" todo-app
          docker push "$APP_IMAGE_TAG"
      
      - name : 'Build and push todo-backend'
        run: |
          echo "BACKEND_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$BACKEND:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
          docker build --tag "$BACKEND_IMAGE_TAG" todo-backend
          docker push "BACKEND_IMAGE_TAG"

      - name : 'Build and push todo-wikipedia'
        run: |
          echo "WIKI_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$WIKI:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
          docker build --tag "$WIKI_IMAGE_TAG" wikipedia
          docker push "$WIKI_IMAGE_TAG"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0
